#pragma kernel MeshColoring

StructuredBuffer<float3> _VertexBuffer;
RWStructuredBuffer<float4> _ColorBuffer;
float4x4 _LocalToWorld;
float4 _Sphere;
uint _VertexCount;

[numthreads(32, 1, 1)]
void MeshColoring(uint id : SV_DispatchThreadID)
{
    if (id >= _VertexCount) {
        return;
    }

    float3 pos = mul(_LocalToWorld, float4(_VertexBuffer[id], 1.0)).xyz;
    float mask = 1.0 - saturate(distance(pos, _Sphere.xyz) / _Sphere.w);

    _ColorBuffer[id] += float4(mask, 0, 0, 1);
}
